#!/usr/bin/env python
# -*- coding: utf-8 -*-
import optparse
import os
import tempfile
import urllib
import urllib2

def main():
    print "Just wanna say [version 1.0]\nRequires mplayer\n"
    usage = 'usage: %prog [options] [phrases]'
    option_list = [
        optparse.make_option('-l', '--language',
            action='store', type='string', dest='language', default='pt'),
    ]
    parser = optparse.OptionParser(usage=usage, option_list=option_list)

    options, phrases = parser.parse_args()

    data = {
        'tl': options.language,
        'q': (u' '.join([i.decode('utf-8') for i in phrases]) or u'nada não').encode('utf-8'),
    }

    url = u'http://translate.google.com/translate_tts?' + urllib.urlencode(data)
    request = urllib2.Request(url)
    request.add_header('User-Agent', 'Mozilla/5.0 (X11; U; Linux i686; pt-BR; rv:1.9.2.17) Gecko/20110422 Ubuntu/10.10 (maverick) Firefox/3.6.17')
    request.add_header('Accept-Charset', 'ISO-8859-1,utf-8;q=0.7,*;q=0.7')
    request.add_header('Accept-Language', 'pt-br,pt;q=0.8,en-us;q=0.5,en;q=0.3')

    webfile = urllib2.urlopen(request)
    localfile = tempfile.NamedTemporaryFile(delete=False)
    localfile.write(webfile.read())

    webfile.close()
    localfile.close()
    print "Playing..."
    os.system('mplayer %s >/dev/null 2>&1' % localfile.name)
    os.unlink(localfile.name)
    print "Done."


if __name__ == '__main__':
    main()
